/*
 * dash_ui.c — pixel-faithful LVGL translation of sim.py
 *
 * Geometry constants are taken verbatim from the Python source.
 * DO NOT "improve" or simplify any coordinate or colour value.
 */
#include "dash_ui.h"
#include "dash_state.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

#define _USE_MATH_DEFINES
#include <math.h>

/* ── Screen dimensions ────────────────────────────────────────────────────── */
#define W  800
#define H  480

/* ── Arc geometry (verbatim from sim.py) ─────────────────────────────────── */
#define ARC_CX_O  788.9f
#define ARC_CY_O  1545.1f
#define ARC_R_UPPER 1483.4f
#define ARC_CX_I  799.4f
#define ARC_CY_I  1609.4f
#define ARC_R_LOWER 1495.2f
#define ARC_A_START (-122.2284f)
#define ARC_A_END   (-89.5713f)
#define MAX_RPM     12000.0f
#define REDLINE_RPM 9500.0f
#define STEPS       600
#define LINE_W      3

/* ── Gear circle ─────────────────────────────────────────────────────────── */
#define CIRCLE_CX  (-16)
#define CIRCLE_CY  239
#define CIRCLE_R   262

/* ── Strip geometry ──────────────────────────────────────────────────────── */
#define ROW1_Y  346
#define ROW2_Y  406
#define STRIP_L 216
#define VCOL_A  454
#define VCOL_B  630
#define VCOL_C  381
#define VCOL_D  575

/* ── Tick label offsets (verbatim) ───────────────────────────────────────── */
#define TICK_LABEL_GLOBAL_OX  10
#define TICK_LABEL_GLOBAL_OY (-28)
#define TICK_LABEL_R  (ARC_R_LOWER + 18.0f)
#define TICK_LIGHT_WIDTH_RPM  600.0f

/* ── Helpers ─────────────────────────────────────────────────────────────── */
static inline float rpm_angle(float rpm) {
    float frac = rpm / MAX_RPM;
    if (frac < 0) frac = 0;
    if (frac > 1) frac = 1;
    return ARC_A_START + frac * (ARC_A_END - ARC_A_START);
}

static inline lv_color_t u32_to_lvc(uint32_t c) {
    return lv_color_make((c>>16)&0xFF,(c>>8)&0xFF,c&0xFF);
}

static inline lv_color_t lerp_col(uint32_t a, uint32_t b, float t) {
    if (t < 0) t = 0; if (t > 1) t = 1;
    uint8_t r = (uint8_t)(((a>>16)&0xFF)*(1-t) + ((b>>16)&0xFF)*t);
    uint8_t g = (uint8_t)(((a>>8 )&0xFF)*(1-t) + ((b>>8 )&0xFF)*t);
    uint8_t bl= (uint8_t)(((a    )&0xFF)*(1-t) + ((b    )&0xFF)*t);
    return lv_color_make(r,g,bl);
}

/* Upper/lower arc sample points */
static void upper_xy(float deg, float *x, float *y) {
    float a = deg * (float)M_PI / 180.0f;
    *x = ARC_CX_O + ARC_R_UPPER * cosf(a);
    *y = ARC_CY_O + ARC_R_UPPER * sinf(a);
}
static void lower_xy(float deg, float *x, float *y) {
    float a = deg * (float)M_PI / 180.0f;
    *x = ARC_CX_I + ARC_R_LOWER * cosf(a);
    *y = ARC_CY_I + ARC_R_LOWER * sinf(a);
}
static void tick_label_xy(float deg, float *x, float *y) {
    float a = deg * (float)M_PI / 180.0f;
    *x = ARC_CX_I + TICK_LABEL_R * cosf(a);
    *y = ARC_CY_I + TICK_LABEL_R * sinf(a);
}

/* ── Cached palette (refreshed on theme change) ──────────────────────────── */
static lv_color_t c_BG, c_RED, c_RED_MED, c_RED_DIM, c_RED_DARK, c_WHITE, c_GREY;
static uint32_t   u_BG, u_RED, u_RED_MED, u_RED_DIM, u_RED_DARK, u_WHITE, u_GREY;
static bool       g_tick_contrast;

static void cache_theme(int idx) {
    const dash_theme_t *t = &DASH_THEMES[idx];
    u_BG=t->BG; u_RED=t->RED; u_RED_MED=t->RED_MED;
    u_RED_DIM=t->RED_DIM; u_RED_DARK=t->RED_DARK;
    u_WHITE=t->WHITE; u_GREY=t->GREY;
    c_BG=u32_to_lvc(u_BG); c_RED=u32_to_lvc(u_RED);
    c_RED_MED=u32_to_lvc(u_RED_MED); c_RED_DIM=u32_to_lvc(u_RED_DIM);
    c_RED_DARK=u32_to_lvc(u_RED_DARK); c_WHITE=u32_to_lvc(u_WHITE);
    c_GREY=u32_to_lvc(u_GREY);
    g_tick_contrast = t->tick_contrast;
}

/* ── Canvas for arc band + hex grid ─────────────────────────────────────── */
#define CB_ARC_W W
#define CB_ARC_H H
static lv_obj_t *cv_hex  = NULL;  /* static hex grid, rebuilt on theme change */
static lv_obj_t *cv_arc  = NULL;  /* redrawn each frame */
static lv_draw_buf_t db_hex, db_arc;
static uint8_t raw_hex[LV_DRAW_BUF_SIZE(CB_ARC_W, CB_ARC_H, LV_COLOR_FORMAT_RGB565)];
static uint8_t raw_arc[LV_DRAW_BUF_SIZE(CB_ARC_W, CB_ARC_H, LV_COLOR_FORMAT_ARGB8888)];

/* ── LVGL label handles ──────────────────────────────────────────────────── */
static lv_obj_t *lbl_speed, *lbl_kmh, *lbl_gear_val, *lbl_gear_lbl;
static lv_obj_t *lbl_odo_label, *lbl_odo_val, *lbl_odo_unit;
static lv_obj_t *lbl_temp_val, *lbl_volt_val;
static lv_obj_t *lbl_range_val, *lbl_eco_val, *lbl_eco_unit, *lbl_time;
/* Separating lines */
static lv_obj_t *line_row1, *line_row2;
static lv_obj_t *line_va, *line_vb, *line_vc, *line_vd;
/* Gear circle */
static lv_obj_t *circle_gear;
/* Dim overlay for brightness */
static lv_obj_t *dim_overlay;

/* ── Fonts (extern — generated by convert_fonts.ps1) ────────────────────── */
LV_FONT_DECLARE(font_roboto_bolditalic_162);
LV_FONT_DECLARE(font_roboto_bolditalic_20);
LV_FONT_DECLARE(font_opensauceone_bold_96);
LV_FONT_DECLARE(font_opensauceone_regular_25);
LV_FONT_DECLARE(font_opensans_regular_28);
LV_FONT_DECLARE(font_opensans_regular_20);
LV_FONT_DECLARE(font_opensans_regular_17);
LV_FONT_DECLARE(font_opensans_bold_26);

/* ── Hex grid ────────────────────────────────────────────────────────────── */
void dash_ui_rebuild_hex(const dash_state_t *s) {
    const dash_theme_t *t = &DASH_THEMES[s->theme_idx];
    lv_canvas_t *cv = (lv_canvas_t *)cv_hex;
    lv_layer_t layer;
    lv_canvas_init_layer(cv_hex, &layer);

    /* fill background */
    lv_draw_rect_dsc_t bg;
    lv_draw_rect_dsc_init(&bg);
    bg.bg_color = u32_to_lvc(t->BG);
    bg.bg_opa   = LV_OPA_COVER;
    lv_area_t full = {0, 0, W-1, H-1};
    lv_draw_rect(&layer, &bg, &full);

    /* hex cells */
    float R   = 27.0f;
    float dx  = R * sqrtf(3.0f);
    float dy  = R * 1.5f;
    uint32_t bg32 = t->BG;
    uint8_t br = ((bg32>>16)&0xFF)/3 + ((bg32>>8)&0xFF)/3 + (bg32&0xFF)/3;
    lv_color_t fill_col, outline_col;
    lv_opa_t   fill_opa, outline_opa;
    if (br < 128) {
        fill_col    = u32_to_lvc(t->RED_DARK);
        outline_col = u32_to_lvc(t->RED_MED);
        fill_opa    = 128; outline_opa = 128;
    } else {
        uint32_t fc = ((((bg32>>16)&0xFF)>15?(((bg32>>16)&0xFF)-15):0)<<16)|
                      ((((bg32>>8 )&0xFF)>15?(((bg32>>8 )&0xFF)-15):0)<<8)|
                       (((bg32    )&0xFF)>15?(((bg32    )&0xFF)-15):0);
        uint32_t oc = ((((bg32>>16)&0xFF)>30?(((bg32>>16)&0xFF)-30):0)<<16)|
                      ((((bg32>>8 )&0xFF)>30?(((bg32>>8 )&0xFF)-30):0)<<8)|
                       (((bg32    )&0xFF)>30?(((bg32    )&0xFF)-30):0);
        fill_col    = u32_to_lvc(fc);
        outline_col = u32_to_lvc(oc);
        fill_opa    = 210; outline_opa = 255;
    }

    lv_draw_rect_dsc_t cell_dsc;
    lv_draw_rect_dsc_init(&cell_dsc);
    cell_dsc.bg_color = fill_col; cell_dsc.bg_opa = fill_opa;
    cell_dsc.border_color = outline_col; cell_dsc.border_opa = outline_opa;
    cell_dsc.border_width = 1;

    int rows = (int)(H / dy) + 4;
    int cols = (int)(W / dx) + 4;
    for (int row = -1; row < rows; row++) {
        for (int ci = -1; ci < cols; ci++) {
            float hx = ci * dx + (row % 2 ? dx / 2.0f : 0.0f);
            float hy = row * dy;
            /* approximate hex as bounding rect — LVGL doesn't support
               arbitrary polygons in draw layer, use triangle pairs instead */
            lv_point_precise_t pts[6];
            for (int i = 0; i < 6; i++) {
                float a = (float)(60*i - 30) * (float)M_PI / 180.0f;
                pts[i].x = (int32_t)(hx + R * cosf(a));
                pts[i].y = (int32_t)(hy + R * sinf(a));
            }
            /* draw as filled polygon via triangle fan */
            lv_draw_triangle_dsc_t tri;
            lv_draw_triangle_dsc_init(&tri);
            tri.bg_color = fill_col; tri.bg_opa = fill_opa;
            for (int i = 1; i < 5; i++) {
                lv_point_precise_t tp[3] = {pts[0], pts[i], pts[i+1]};
                tri.p[0]=pts[0]; tri.p[1]=pts[i]; tri.p[2]=pts[i+1];
                lv_draw_triangle(&layer, &tri);
            }
            /* outline — draw 6 lines */
            lv_draw_line_dsc_t ld;
            lv_draw_line_dsc_init(&ld);
            ld.color = outline_col; ld.opa = outline_opa; ld.width = 1;
            for (int i = 0; i < 6; i++) {
                ld.p1 = pts[i]; ld.p2 = pts[(i+1)%6];
                lv_draw_line(&layer, &ld);
            }
        }
    }
    lv_canvas_finish_layer(cv_hex, &layer);
}

/* ── Arc band draw (onto cv_arc canvas each frame) ───────────────────────── */
static void draw_arc_band_canvas(float rpm) {
    lv_layer_t layer;
    lv_canvas_init_layer(cv_arc, &layer);

    /* clear transparent */
    lv_draw_rect_dsc_t clr;
    lv_draw_rect_dsc_init(&clr);
    clr.bg_color = lv_color_black(); clr.bg_opa = LV_OPA_TRANSP;
    lv_area_t full = {0,0,W-1,H-1};
    lv_draw_rect(&layer, &clr, &full);

    float target_a = rpm_angle(rpm);

    lv_draw_triangle_dsc_t td;
    lv_draw_triangle_dsc_init(&td);
    lv_draw_line_dsc_t ld;
    lv_draw_line_dsc_init(&ld);

    /* -- background (RED_DARK) band across full arc -- */
    td.bg_color = c_RED_DARK; td.bg_opa = LV_OPA_COVER;
    for (int i = 0; i < STEPS; i++) {
        float a0 = ARC_A_START + (float)i     / STEPS * (ARC_A_END - ARC_A_START);
        float a1 = ARC_A_START + (float)(i+1) / STEPS * (ARC_A_END - ARC_A_START);
        float ux0,uy0,ux1,uy1,lx0,ly0,lx1,ly1;
        upper_xy(a0,&ux0,&uy0); upper_xy(a1,&ux1,&uy1);
        lower_xy(a0,&lx0,&ly0); lower_xy(a1,&lx1,&ly1);
        /* quad as two triangles */
        td.p[0].x=(int32_t)ux0; td.p[0].y=(int32_t)uy0;
        td.p[1].x=(int32_t)ux1; td.p[1].y=(int32_t)uy1;
        td.p[2].x=(int32_t)lx1; td.p[2].y=(int32_t)ly1;
        lv_draw_triangle(&layer, &td);
        td.p[1].x=(int32_t)lx0; td.p[1].y=(int32_t)ly0;
        td.p[2].x=(int32_t)lx1; td.p[2].y=(int32_t)ly1;
        lv_draw_triangle(&layer, &td);
    }

    /* -- lit (RED) band up to target_angle -- */
    if (target_a > ARC_A_START + 1e-4f) {
        int n_lit = (int)ceilf(STEPS * (target_a - ARC_A_START) / (ARC_A_END - ARC_A_START));
        if (n_lit > STEPS) n_lit = STEPS;
        td.bg_color = c_RED;
        for (int i = 0; i < n_lit; i++) {
            float a0 = ARC_A_START + (float)i     / STEPS * (ARC_A_END - ARC_A_START);
            float a1 = ARC_A_START + (float)(i+1) / STEPS * (ARC_A_END - ARC_A_START);
            float ux0,uy0,ux1,uy1,lx0,ly0,lx1,ly1;
            upper_xy(a0,&ux0,&uy0); upper_xy(a1,&ux1,&uy1);
            lower_xy(a0,&lx0,&ly0); lower_xy(a1,&lx1,&ly1);
            td.p[0].x=(int32_t)ux0; td.p[0].y=(int32_t)uy0;
            td.p[1].x=(int32_t)ux1; td.p[1].y=(int32_t)uy1;
            td.p[2].x=(int32_t)lx1; td.p[2].y=(int32_t)ly1;
            lv_draw_triangle(&layer, &td);
            td.p[1].x=(int32_t)lx0; td.p[1].y=(int32_t)ly0;
            td.p[2].x=(int32_t)lx1; td.p[2].y=(int32_t)ly1;
            lv_draw_triangle(&layer, &td);
        }
    }

    /* -- upper outline -- */
    ld.color = c_RED; ld.opa = LV_OPA_COVER; ld.width = LINE_W;
    for (int i = 0; i < STEPS; i++) {
        float a0 = ARC_A_START + (float)i     / STEPS * (ARC_A_END - ARC_A_START);
        float a1 = ARC_A_START + (float)(i+1) / STEPS * (ARC_A_END - ARC_A_START);
        float x0,y0,x1,y1;
        upper_xy(a0,&x0,&y0); upper_xy(a1,&x1,&y1);
        ld.p1.x=(int32_t)x0; ld.p1.y=(int32_t)y0;
        ld.p2.x=(int32_t)x1; ld.p2.y=(int32_t)y1;
        lv_draw_line(&layer, &ld);
    }

    /* -- lower outline -- */
    ld.width = LINE_W > 1 ? LINE_W-1 : 1;
    for (int i = 0; i < STEPS; i++) {
        float a0 = ARC_A_START + (float)i     / STEPS * (ARC_A_END - ARC_A_START);
        float a1 = ARC_A_START + (float)(i+1) / STEPS * (ARC_A_END - ARC_A_START);
        float x0,y0,x1,y1;
        lower_xy(a0,&x0,&y0); lower_xy(a1,&x1,&y1);
        ld.p1.x=(int32_t)x0; ld.p1.y=(int32_t)y0;
        ld.p2.x=(int32_t)x1; ld.p2.y=(int32_t)y1;
        lv_draw_line(&layer, &ld);
    }

    /* -- major tick marks -- */
    static const float tick_rpms[5] = {2000,4000,6000,8000,10000};
    lv_color_t tick_lit = g_tick_contrast
        ? lv_color_make(255-(u_WHITE>>16&0xFF),255-(u_WHITE>>8&0xFF),255-(u_WHITE&0xFF))
        : c_WHITE;
    ld.width = LINE_W > 1 ? LINE_W/2 : 1;
    for (int ti = 0; ti < 5; ti++) {
        float tr = tick_rpms[ti];
        float a  = rpm_angle(tr);
        float ux,uy,lx,ly;
        upper_xy(a,&ux,&uy); lower_xy(a,&lx,&ly);
        float thickness = sqrtf((ux-lx)*(ux-lx)+(uy-ly)*(uy-ly));
        int out_len = (int)(fmaxf(4.0f,(thickness+6.0f)*0.5f));
        float t_val = (rpm - tr + TICK_LIGHT_WIDTH_RPM) / (2.0f * TICK_LIGHT_WIDTH_RPM);
        if (t_val<0) t_val=0; if (t_val>1) t_val=1;
        ld.color = lerp_col(u_RED, g_tick_contrast?
            (0xFF000000|(255-(u_WHITE>>16&0xFF))<<16|(255-(u_WHITE>>8&0xFF))<<8|(255-(u_WHITE&0xFF))) : u_WHITE,
            t_val);
        ld.p1.x=(int32_t)lx; ld.p1.y=(int32_t)ly;
        ld.p2.x=(int32_t)lx; ld.p2.y=(int32_t)(ly - out_len);
        lv_draw_line(&layer, &ld);
    }

    /* -- subtick marks -- */
    ld.width = 1;
    for (int tr = 500; tr < (int)MAX_RPM; tr += 500) {
        if (tr==2000||tr==4000||tr==6000||tr==8000||tr==10000) continue;
        float a = rpm_angle((float)tr);
        float lx,ly;
        lower_xy(a,&lx,&ly);
        int out_len = (tr % 1000 == 0) ? 18 : 10;
        float t_val = (rpm - tr + TICK_LIGHT_WIDTH_RPM) / (2.0f * TICK_LIGHT_WIDTH_RPM);
        if (t_val<0) t_val=0; if (t_val>1) t_val=1;
        uint32_t tw = g_tick_contrast?
            (0xFF000000|(255-(u_WHITE>>16&0xFF))<<16|(255-(u_WHITE>>8&0xFF))<<8|(255-(u_WHITE&0xFF))): u_WHITE;
        ld.color = lerp_col(u_RED, tw, t_val);
        ld.p1.x=(int32_t)lx; ld.p1.y=(int32_t)ly;
        ld.p2.x=(int32_t)lx; ld.p2.y=(int32_t)(ly - out_len);
        lv_draw_line(&layer, &ld);
    }

    lv_canvas_finish_layer(cv_arc, &layer);
}

/* ── Strip line helpers ───────────────────────────────────────────────────── */
static void set_line(lv_obj_t *obj, int x1,int y1,int x2,int y2) {
    static lv_point_precise_t pts[2];
    /* each line obj has its own static pts — use obj userdata trick:
       store pts inside lv_obj userdata to avoid aliasing */
    lv_point_precise_t *p = (lv_point_precise_t*)lv_obj_get_user_data(obj);
    if (!p) {
        p = lv_malloc(2*sizeof(lv_point_precise_t));
        lv_obj_set_user_data(obj, p);
    }
    p[0].x=x1; p[0].y=y1; p[1].x=x2; p[1].y=y2;
    lv_line_set_points(obj, p, 2);
}

/* ── UI init ─────────────────────────────────────────────────────────────── */
void dash_ui_init(void) {
    cache_theme(0);
    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, c_BG, 0);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

    /* hex grid canvas */
    lv_draw_buf_init(&db_hex, W, H, LV_COLOR_FORMAT_RGB565, LV_STRIDE_AUTO, raw_hex, sizeof(raw_hex));
    cv_hex = lv_canvas_create(scr);
    lv_canvas_set_draw_buf(cv_hex, &db_hex);
    lv_obj_set_pos(cv_hex, 0, 0);

    /* arc canvas (ARGB so transparent outside arc region) */
    lv_draw_buf_init(&db_arc, W, H, LV_COLOR_FORMAT_ARGB8888, LV_STRIDE_AUTO, raw_arc, sizeof(raw_arc));
    cv_arc = lv_canvas_create(scr);
    lv_canvas_set_draw_buf(cv_arc, &db_arc);
    lv_obj_set_pos(cv_arc, 0, 0);

    /* strip separator lines */
    static lv_style_t line_style;
    lv_style_init(&line_style);
    lv_style_set_line_color(&line_style, c_RED);
    lv_style_set_line_width(&line_style, LINE_W);
    lv_style_set_line_opa(&line_style, LV_OPA_COVER);

    #define MKLINE(var) \
        var = lv_line_create(scr); \
        lv_obj_add_style(var, &line_style, 0);

    MKLINE(line_row1); MKLINE(line_row2);
    MKLINE(line_va);   MKLINE(line_vb);
    MKLINE(line_vc);   MKLINE(line_vd);

    /* gear circle */
    circle_gear = lv_obj_create(scr);
    lv_obj_set_size(circle_gear, CIRCLE_R*2, CIRCLE_R*2);
    lv_obj_set_pos(circle_gear, CIRCLE_CX - CIRCLE_R, CIRCLE_CY - CIRCLE_R);
    lv_obj_set_style_radius(circle_gear, CIRCLE_R, 0);
    lv_obj_set_style_bg_color(circle_gear, c_BG, 0);
    lv_obj_set_style_bg_opa(circle_gear, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(circle_gear, c_RED, 0);
    lv_obj_set_style_border_width(circle_gear, LINE_W, 0);
    lv_obj_set_style_border_opa(circle_gear, LV_OPA_COVER, 0);

    /* speed label */
    lbl_speed = lv_label_create(scr);
    lv_obj_set_style_text_font(lbl_speed, &font_roboto_bolditalic_162, 0);
    lv_obj_set_style_text_color(lbl_speed, c_WHITE, 0);

    /* km/h label */
    lbl_kmh = lv_label_create(scr);
    lv_obj_set_style_text_font(lbl_kmh, &font_opensans_regular_28, 0);
    lv_obj_set_style_text_color(lbl_kmh, c_GREY, 0);
    lv_label_set_text(lbl_kmh, "km/h");

    /* gear value */
    lbl_gear_val = lv_label_create(scr);
    lv_obj_set_style_text_font(lbl_gear_val, &font_opensauceone_bold_96, 0);

    /* gear label */
    lbl_gear_lbl = lv_label_create(scr);
    lv_obj_set_style_text_font(lbl_gear_lbl, &font_opensauceone_regular_25, 0);
    lv_obj_set_style_text_color(lbl_gear_lbl, c_WHITE, 0);
    lv_label_set_text(lbl_gear_lbl, "GEAR");
    lv_obj_set_pos(lbl_gear_lbl,
        86 - lv_font_get_glyph_width(&font_opensauceone_regular_25,'G',0)/2,
        57 - 25/2);

    /* strip labels */
    #define MKLBL(var, font, color) \
        var = lv_label_create(scr); \
        lv_obj_set_style_text_font(var, font, 0); \
        lv_obj_set_style_text_color(var, color, 0);

    MKLBL(lbl_odo_label, &font_opensans_regular_20,  c_GREY);
    MKLBL(lbl_odo_val,   &font_opensans_bold_26,     c_WHITE);
    MKLBL(lbl_odo_unit,  &font_opensans_regular_17,  c_GREY);
    MKLBL(lbl_temp_val,  &font_opensans_bold_26,     c_WHITE);
    MKLBL(lbl_volt_val,  &font_opensans_bold_26,     c_WHITE);
    MKLBL(lbl_range_val, &font_opensans_bold_26,     c_WHITE);
    MKLBL(lbl_eco_val,   &font_opensans_bold_26,     c_WHITE);
    MKLBL(lbl_eco_unit,  &font_opensans_regular_17,  c_GREY);
    MKLBL(lbl_time,      &font_opensans_bold_26,     c_WHITE);

    /* dim overlay */
    dim_overlay = lv_obj_create(scr);
    lv_obj_set_size(dim_overlay, W, H);
    lv_obj_set_pos(dim_overlay, 0, 0);
    lv_obj_set_style_bg_color(dim_overlay, lv_color_black(), 0);
    lv_obj_set_style_bg_opa(dim_overlay, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(dim_overlay, 0, 0);
    lv_obj_set_style_radius(dim_overlay, 0, 0);
}

/* ── UI apply theme ──────────────────────────────────────────────────────── */
void dash_ui_apply_theme(int idx) {
    cache_theme(idx);
    lv_obj_t *scr = lv_screen_active();
    lv_obj_set_style_bg_color(scr, c_BG, 0);

    lv_obj_set_style_text_color(lbl_speed,    c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_kmh,      c_GREY,  0);
    lv_obj_set_style_text_color(lbl_gear_lbl, c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_odo_label,c_GREY,  0);
    lv_obj_set_style_text_color(lbl_odo_val,  c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_odo_unit, c_GREY,  0);
    lv_obj_set_style_text_color(lbl_temp_val, c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_volt_val, c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_range_val,c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_eco_val,  c_WHITE, 0);
    lv_obj_set_style_text_color(lbl_eco_unit, c_GREY,  0);
    lv_obj_set_style_text_color(lbl_time,     c_WHITE, 0);

    lv_obj_set_style_bg_color(circle_gear,     c_BG,  0);
    lv_obj_set_style_border_color(circle_gear, c_RED, 0);

    /* line colours updated via style — need direct set since shared style */
    /* simplest: set inline style on each */
    lv_obj_t *lines[] = {line_row1,line_row2,line_va,line_vb,line_vc,line_vd};
    for (int i=0;i<6;i++) lv_obj_set_style_line_color(lines[i], c_RED, 0);
}

/* ── Cell layout helper ──────────────────────────────────────────────────── */
/* Positions label+value+unit horizontally centred on (cx,cy).
   Unit is placed at bottom-right of value with UNIT_OFFSET_Y = -4 */
#define UNIT_OFFSET_Y (-4)
static void position_cell(lv_obj_t *lbl, lv_obj_t *val, lv_obj_t *unit,
                           int cx, int cy) {
    int wl = lbl  ? lv_obj_get_width(lbl)  : 0;
    int wv = val  ? lv_obj_get_width(val)  : 0;
    int wu = unit ? lv_obj_get_width(unit) : 0;
    int hl = lbl  ? lv_obj_get_height(lbl)  : 0;
    int hv = val  ? lv_obj_get_height(val)  : 0;
    int hu = unit ? lv_obj_get_height(unit) : 0;
    int gap = 8;
    int w_total = wl + (wl?gap:0) + wv + (wu?5+wu:0);
    int x = cx - w_total/2;
    if (lbl)  { lv_obj_set_pos(lbl,  x, cy - hl/2); x += wl + gap; }
    if (val)  { lv_obj_set_pos(val,  x, cy - hv/2); }
    if (unit) { lv_obj_set_pos(unit, x + wv + 5,
                    cy + hv/2 - hu + UNIT_OFFSET_Y); }
}

/* ── Tick label positions ─────────────────────────────────────────────────── */
static lv_obj_t *tick_labels[5];
static const float tick_rpms_lbl[5] = {2000,4000,6000,8000,10000};
static const char *tick_strs[5]     = {"2","4","6","8","10"};
static const float tick_ox[5] = {0,0,-4,-4,-4};
static const float tick_oy[5] = {0,0,3.5f,3.5f,3.5f};

/* ── Full update ─────────────────────────────────────────────────────────── */
void dash_ui_update(const dash_state_t *s) {
    if (s->rebuild_hex)
        dash_ui_rebuild_hex(s);

    cache_theme(s->theme_idx);

    /* -- arc band -- */
    draw_arc_band_canvas(s->disp_rpm);

    /* -- tick label colours & positions -- */
    uint32_t tw = g_tick_contrast ?
        (0xFF000000|((255-(u_WHITE>>16&0xFF))<<16)|((255-(u_WHITE>>8&0xFF))<<8)|(255-(u_WHITE&0xFF))) : u_WHITE;
    for (int ti=0;ti<5;ti++) {
        if (!tick_labels[ti]) {
            tick_labels[ti] = lv_label_create(lv_screen_active());
            lv_obj_set_style_text_font(tick_labels[ti], &font_roboto_bolditalic_20, 0);
            lv_label_set_text(tick_labels[ti], tick_strs[ti]);
        }
        float a = rpm_angle(tick_rpms_lbl[ti]);
        float lx,ly;
        tick_label_xy(a,&lx,&ly);
        lx += TICK_LABEL_GLOBAL_OX + tick_ox[ti];
        ly += TICK_LABEL_GLOBAL_OY + tick_oy[ti];
        float t_val = (s->disp_rpm - tick_rpms_lbl[ti] + TICK_LIGHT_WIDTH_RPM)
                    / (2.0f * TICK_LIGHT_WIDTH_RPM);
        if (t_val<0) t_val=0; if (t_val>1) t_val=1;
        lv_color_t col = lerp_col(u_RED, tw, t_val);
        lv_obj_set_style_text_color(tick_labels[ti], col, 0);
        int tw2 = lv_obj_get_width(tick_labels[ti]);
        int th  = lv_obj_get_height(tick_labels[ti]);
        lv_obj_set_pos(tick_labels[ti], (int32_t)(lx - tw2/2), (int32_t)(ly - th/2));
    }

    /* -- speed -- */
    char spd_buf[8]; snprintf(spd_buf, sizeof(spd_buf), "%d", (int)s->disp_speed);
    lv_label_set_text(lbl_speed, spd_buf);
    lv_color_t spd_col = s->blink_on ? lv_color_make(255,49,49) : c_WHITE;
    lv_color_t kmh_col = s->blink_on ? lv_color_make(255,49,49) : c_GREY;
    lv_obj_set_style_text_color(lbl_speed, spd_col, 0);
    lv_obj_set_style_text_color(lbl_kmh,   kmh_col, 0);
    /* position: right-align speed to x=683, vcenter at y=233 */
    int sw = lv_obj_get_width(lbl_speed);
    int sh = lv_obj_get_height(lbl_speed);
    lv_obj_set_pos(lbl_speed, 683 - sw, 233 - sh/2);
    int uw = lv_obj_get_width(lbl_kmh);
    int uh = lv_obj_get_height(lbl_kmh);
    lv_obj_set_pos(lbl_kmh, 682, 271 - uh/2);

    /* -- gear -- */
    lv_label_set_text(lbl_gear_val, s->gear);
    lv_color_t gc = (s->gear[0]=='N') ? c_RED : c_WHITE;
    lv_obj_set_style_text_color(lbl_gear_val, gc, 0);
    int gw = lv_obj_get_width(lbl_gear_val);
    int gh = lv_obj_get_height(lbl_gear_val);
    lv_obj_set_pos(lbl_gear_val, 86 - gw/2, 127 - gh/2);

    /* -- strip separators -- */
    set_line(line_row1, STRIP_L, ROW1_Y, W,      ROW1_Y);
    set_line(line_row2, 0,       ROW2_Y, W,      ROW2_Y);
    set_line(line_va,   VCOL_A,  ROW1_Y, VCOL_A, ROW2_Y);
    set_line(line_vb,   VCOL_B,  ROW1_Y, VCOL_B, ROW2_Y);
    set_line(line_vc,   VCOL_C,  ROW2_Y, VCOL_C, H);
    set_line(line_vd,   VCOL_D,  ROW2_Y, VCOL_D, H);

    /* -- ODO / TRIP -- */
    static const char *odo_labels[3] = {"ODO","TRIP A","TRIP B"};
    char odo_val_buf[16];
    double odo_val = (s->odo_mode==0)?s->odo:(s->odo_mode==1)?s->trip_a:s->trip_b;
    snprintf(odo_val_buf, sizeof(odo_val_buf), "%.2f", odo_val);
    lv_label_set_text(lbl_odo_label, odo_labels[s->odo_mode]);
    lv_label_set_text(lbl_odo_val,   odo_val_buf);
    lv_label_set_text(lbl_odo_unit,  "km");
    int cy1 = (ROW1_Y + ROW2_Y)/2;
    position_cell(lbl_odo_label, lbl_odo_val, lbl_odo_unit, (STRIP_L+VCOL_A)/2, cy1);

    /* -- TEMP -- */
    char temp_buf[8]; snprintf(temp_buf,sizeof(temp_buf),"%d",(int)s->temp);
    lv_label_set_text(lbl_temp_val, temp_buf);
    /* reuse odo_label slot for "TEMP" text — create separate static label */
    /* (icon_temp not available in LVGL ver — use text label "TEMP") */
    position_cell(NULL, lbl_temp_val, NULL, (VCOL_A+VCOL_B)/2, cy1);

    /* -- VOLT -- */
    char volt_buf[8]; snprintf(volt_buf,sizeof(volt_buf),"%.1f",s->volt);
    lv_label_set_text(lbl_volt_val, volt_buf);
    position_cell(NULL, lbl_volt_val, NULL, (VCOL_B+W)/2, cy1);

    /* -- RANGE -- */
    char range_buf[8]; snprintf(range_buf,sizeof(range_buf),"%d",s->range);
    lv_label_set_text(lbl_range_val, range_buf);
    int cy2 = (ROW2_Y + H)/2;
    position_cell(NULL, lbl_range_val, NULL, (STRIP_L+VCOL_C)/2, cy2);

    /* -- ECO -- */
    char eco_buf[12], eco_unit_buf[12];
    if (s->eco_imperial) {
        float mpg = s->eco > 0 ? 282.5f / s->eco : 0;
        snprintf(eco_buf,  sizeof(eco_buf),  "%.1f", mpg);
        snprintf(eco_unit_buf, sizeof(eco_unit_buf), "mpg");
    } else {
        snprintf(eco_buf,  sizeof(eco_buf),  "%d", s->eco);
        snprintf(eco_unit_buf, sizeof(eco_unit_buf), "L/100km");
    }
    lv_label_set_text(lbl_eco_val,  eco_buf);
    lv_label_set_text(lbl_eco_unit, eco_unit_buf);
    position_cell(NULL, lbl_eco_val, lbl_eco_unit, (VCOL_C+VCOL_D)/2, cy2);

    /* -- TIME -- */
    lv_label_set_text(lbl_time, s->time_str);
    int tw3 = lv_obj_get_width(lbl_time);
    int th3 = lv_obj_get_height(lbl_time);
    lv_obj_set_pos(lbl_time, (VCOL_D+W)/2 - tw3/2, cy2 - th3/2);

    /* -- dim overlay -- */
    lv_opa_t dim_opa = (s->brightness < 1.0f)
        ? (lv_opa_t)((1.0f - s->brightness) * 255)
        : LV_OPA_TRANSP;
    lv_obj_set_style_bg_opa(dim_overlay, dim_opa, 0);
}
